### ISSUE TITLE
error when I have a emoji as answer

### ISSUE THREAD

**Issue by angelspawn** [Netfreak25/Sam#2]
When I have an emoji as answer to a question I receive the folling error:
Fehler Location: 'ascii' codec can't encode character u'\U0001f600' in position 0: ordinal not in range(128)

I have tried with one correct and two wrong answers and I always get this kind of error.
I will try with only one wrong answer if I can reproduce the error.

**Comment by angelspawn** [comment]
Same issue with only wrong answer so it seems to be the issue if you have a ":" as start of the answer

**Comment by Netfreak25** [comment]
fixed

**Comment by angelspawn** [comment]
Thanks for the quick fix :)
